Repository wecode-bootcamp-korea/39-2nd-stawefolio-frontend, pull requests merged in 2022-12, with the labels that each got.

#5 [39기 김동기] Add:Main page 완료
  package-lock.json
  package.json
  public/favicon.ico
  public/images/kimdongki/camping.jpg
  public/images/kimdongki/date.jpeg
  public/images/kimdongki/jeju.jpg
  public/images/kimdongki/kitchen.jpg
  public/images/kimdongki/love.jpeg
  public/images/kimdongki/one-room.jpg
  public/images/kimdongki/rain.jpeg
  public/images/kimdongki/story.jpeg
  public/images/kimdongki/swim.jpg
  public/images/kimdongki/swimming.jpg
  public/images/kimdongki/t-shirts-1.jpg
  public/images/kimdongki/walk.jpeg
  public/images/kimdongki/you.jpeg
  src/pages/Main/Main.js
  src/pages/Main/Vibes.js
  src/styles/GlobalStyle.js
Labels: 완료

#6 [39기 김동기]Add:Room Card Layout
  public/images/kimdongki/kit.jpg
  src/components/RoomCard/RoomCard.js
Labels: 멘토 리뷰 요청

#1 [39기 김동기] Add:Nav layout완료
  package-lock.json
  package.json
  public/favicon.ico
  public/images/NavImages/arw-search.png
  public/images/NavImages/btn-close.png
  public/images/NavImages/ico-search.png
  public/images/NavImages/logo.jpg
  public/images/NavImages/when.png
  public/images/NavImages/where.png
  public/index.html
  src/components/Nav/Nav.js
  src/components/Nav/WhenTo.js
  src/components/Nav/WhereTo.js
  src/pages/Main/Main.js
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: 수정 요청

#9 [39기 구수정] RoomList 숙소 리스트들을 보여주고 필터링, 정렬 기능 제공
  package-lock.json
  package.json
  public/data/InfoListData.json
  public/images/roomList/arw-search.png
  public/images/roomList/arw_select.png
  public/images/roomList/kit.jpg
  src/Router.js
  src/components/DayPicker/CustomInput.js
  src/components/DayPicker/DayPicker.js
  src/config.js
  src/pages/RoomList/DropDown/DropDown.js
  src/pages/RoomList/DropDown/People.js
  src/pages/RoomList/DropDown/PriceRange.js
  src/pages/RoomList/DropDown/Stay.js
  src/pages/RoomList/DropDown/Theme.js
  src/pages/RoomList/Room.js
  src/pages/RoomList/RoomList.js
Labels: Conflict 해결 요청

#4 [39기 구수정] Booking 숙소 정보 및 위치 안내
  README.md
  package-lock.json
  package.json
  public/data/roomData.json
  public/images/furniture.jpg
  public/index.html
  src/components/DayPicker/CustomInput.js
  src/images/booking/furniture.jpg
  src/images/t-shirts-1.jpg
  src/pages/Booking/Booking.js
  src/pages/RoomList/DropDown/PriceRange.js
Labels: Conflict 해결 요청, 도움 요청

#10 [39기 안상준] Add:Footer Layout & 기능 구현 완료
  public/images/footer/GithubLogo.png
  public/images/footer/NotionLogo.png
  public/images/footer/TeamLogo.png
  src/components/Footer/Footer.js
Labels: Conflict 해결 요청, Rebase 요청

#3 [39기 안상준] Add:Login Page Layout 완료
  .gitignore
  public/data/BookingData.json
  public/images/Login/kakao-login.png
  public/images/Login/kakao-login2.png
  public/images/Mypage/JEJU.jpeg
  public/images/Mypage/traveler.png
  src/Router.js
  src/pages/Login/Hooks/useFetch.js
  src/pages/Login/Login.js
  src/pages/Login/LoginCode.js
  src/pages/Login/OAuth.js
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청, 추가 기능 구현 중
